### ISSUE TITLE
（更新报告

### ISSUE THREAD

**Issue by youruoxiao** [shenjackyuanjie/Difficult-Rocket#2]
When is the closed alpha？
ps:u are so lovely,so i'll give a star to you!

**Comment by shenjackyuanjie** [comment]
rua！
thanks for star!
well. now I'm making for textures and some other things
alpha will come in ...... about a month 😂
(because is I dose not make it in month, I'll have no time to make
(王师北定中原日，家祭毋忘告乃翁的翻译也太离谱了点

**Comment by ruoxiao-you** [comment]
okkkk,thank for you answers.
i hope it will be a good project

**Comment by shenjackyuanjie** [comment]
well, can you write python?
if you can , welcome to join our team(is not also welcome)
QQ team:1027459267
my QQ:3695888

**Comment by ruoxiao-you** [comment]
sorry...i can't

**Comment by shenjackyuanjie** [comment]
well... if you like to join us for just a talk
then we will be very welcome

**Comment by shenjackyuanjie** [comment]
i'm preapring a DEMO now will be release in a few days

**Comment by ruoxiao-you** [comment]
six days later…
what's the meaning"a few days"in your mind.

**Comment by shenjackyuanjie** [comment]
reeeee just mean comming soooooooon

**Comment by ruoxiao-you** [comment]
🤔

**Comment by shenjackyuanjie** [comment]
更着呢（

**Comment by shenjackyuanjie** [comment]
command line!

**Comment by shenjackyuanjie** [comment]
这玩意也还是先咕咕咕了

**Comment by shenjackyuanjie** [comment]
咋说呢，0.7.0.2 更新了！
